-- MySQL Script generated by MySQL Workbench
-- Tue Nov  7 16:04:16 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema instaMane
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema instaMane
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `instaMane` DEFAULT CHARACTER SET utf8 ;
USE `instaMane` ;

-- -----------------------------------------------------
-- Table `instaMane`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `instaMane`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `nickname` VARCHAR(255) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `icon` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `nickname_UNIQUE` (`nickname` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `instaMane`.`articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `instaMane`.`articles` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `users_id` INT UNSIGNED NOT NULL,
  `content` VARCHAR(255) NULL DEFAULT NULL,
  `created` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_articles_authors2_idx` (`users_id` ASC),
  CONSTRAINT `fk_articles_authors2`
    FOREIGN KEY (`users_id`)
    REFERENCES `instaMane`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `instaMane`.`pics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `instaMane`.`pics` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `articles_id` INT UNSIGNED NOT NULL,
  `url` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pics_articles1_idx` (`articles_id` ASC),
  UNIQUE INDEX `url_UNIQUE` (`url` ASC),
  CONSTRAINT `fk_pics_articles1`
    FOREIGN KEY (`articles_id`)
    REFERENCES `instaMane`.`articles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `instaMane`.`likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `instaMane`.`likes` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `users_id` INT UNSIGNED NOT NULL,
  `articles_id` INT UNSIGNED NOT NULL,
  `up` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_likes_articles1_idx` (`articles_id` ASC),
  INDEX `fk_likes_authors1_idx` (`users_id` ASC),
  CONSTRAINT `fk_likes_articles1`
    FOREIGN KEY (`articles_id`)
    REFERENCES `instaMane`.`articles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_likes_authors1`
    FOREIGN KEY (`users_id`)
    REFERENCES `instaMane`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `instaMane`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `instaMane`.`comments` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `users_id` INT UNSIGNED NOT NULL,
  `articles_id` INT UNSIGNED NOT NULL,
  `content` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comments_articles1_idx` (`articles_id` ASC),
  INDEX `fk_comments_authors1_idx` (`users_id` ASC),
  CONSTRAINT `fk_comments_articles1`
    FOREIGN KEY (`articles_id`)
    REFERENCES `instaMane`.`articles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_authors1`
    FOREIGN KEY (`users_id`)
    REFERENCES `instaMane`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
